name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: chmod +x lt.sh && ./lt.sh "ci_session=f9c4d4295cba98fddf31da457eae6797d496945d; csrf_cookie_name=ea3d1b9000c9c24541fb8bbcb1f7cf67" "itssarari@gmail.com"
